feat(package): pre-commit testing

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,4 +1,13 @@
 #!/usr/bin/env sh
 . "$(dirname -- "$0")/_/husky.sh"
 
+
+npx nx run-many -t test --bail --findRelatedTests=$STAGED_FILES
+if [[ "$?" == 0 ]]; then
+    echo "\t\033[32mJest Tests Passed\033[0m"
+else
+    echo "\t\033[41mJest Tests Failed\033[0m"
+    PASS=false
+fi
+
 npx lint-staged
